### ISSUE TITLE
Great Demo! Question about rotating the iPhone

### ISSUE THREAD

**Issue by RickTheHat** [ufukhawk/Chased-Home-UI-Design#1]
Just started playing around with the design you created and I like it.

Wondering about landscape mode as it looks like I have lost the text below the image. Want to see if you had a quick fix for this before I start to spend lots of time debugging.

Thanks! Looks awesome!

<img width="659" alt="CapturFiles-20210214_090715" src="https://user-images.githubusercontent.com/704833/107880444-6bf76780-6ea4-11eb-8364-b61378293e34.png">

**Comment by RickTheHat** [comment]
In my testing, added a third row and made a change to the row definition to all be "Auto" which made the text appear in landscape mode & on the iPad. Not sure if that's the best way to do it but it solves the disappearing text issue.

<img width="540" alt="CapturFiles-20210214_092801" src="https://user-images.githubusercontent.com/704833/107880888-37d17600-6ea7-11eb-81c7-a51f7ff02f2a.png">

**Comment by ufukhawk** [comment]
Hi Rick!

A practical solution! Thanks!
